### ISSUE TITLE
308 - 322 missing from class_curation sheet

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/whole_human_brain_ontology#7]
https://github.com/hkir-dev/whole_human_brain_ontology/blob/main/src/patterns/data/default/CS202210140_class_curation.tsv#L286

<img width="517" alt="image" src="https://github.com/hkir-dev/whole_human_brain_ontology/assets/112839/6618893f-5f3d-4ade-93b5-e6a3c53a38ce">

Would like to add some classifications to cells in this range based on `Subtype auto-annotation`

Judging from the line numbers, some other ranges missing too.  Haven't checked other tables.

**Comment by hkir-dev** [comment]
That missing id range belongs to `Upper rhombic lip`, `Lower rhombic lip`, `Splatter` and `Miscellaneous`
![image](https://github.com/hkir-dev/whole_human_brain_ontology/assets/73784267/375017f7-59fd-4367-9e4b-8f8396c09450)

In the [taxonomy_details config](https://github.com/hkir-dev/whole_human_brain_ontology/blob/main/src/dendrograms/taxonomy_details.yaml), I couldn't find CL gross classifications for them, so they are disabled for now.

**Comment by hkir-dev** [comment]
Generic mappings to the CL:0000540 (neuron) class added with https://github.com/hkir-dev/whole_human_brain_ontology/pull/8
